### ISSUE TITLE
Provide more specific error messages

### ISSUE THREAD

**Issue by shalvah** [shalvah/unn-api#4]
Currently, if the project fails to extract the user's details from the UNN portal login response, it assumes incorrect details were provided and returns `{"status":"failed","message":"authentication failed: incorrect username or password"}`

Unfortunately, this is misleading. Sometimes, the login details might be correct but the DOM on the portal has been changed, so parsing failed. In such a case, we need to be able to identify this and respond with a proper error message that indicates what happened.

**Comment by MartinsOnuoha** [comment]
The `{"status":"failed","message":"authentication failed: incorrect username or password"}` response seems to be coming from the `Handler.php` helper. 
However limited my knowledge in PHP is.
If changes in the DOM affects the user credentials I'm guessing we're using `clientside validation`?. If this is true, we might want to send the requests to the server instead. however I do not think this is the case.

**Comment by shalvah** [comment]
It's a web scraper, so we can't send stuff directly to the server.
Basically, we pretend to be a browser, ask it for the login page, get the
details we need and simulate a login. It should then send us the profile
page when we're logged in.
Try taking a look at the source (app/Http/Controllers/HomeCobtroller, I
think) to get a feel of what we're doing.

>

**Comment by shalvah** [comment]
Fixed in 6eb66b86fcdd30d45a859cad6968f8c8fcbfcfbd and d0e3722529d0d5cc22f09d88edf90e69c095e335.
