### ISSUE TITLE
De-version this API and rename endpoint

### ISSUE THREAD

**Issue by shalvah** [shalvah/unn-api#6]
The API currently lives at `/v1`
When I built this, I thought versioning was always the way. In retrospect, versioning here is irrelevant. That's because this API is only a wrapper for a web scraper, and should change whenever the portal changes. 
We should move it to the root directory.
Also, the endpoint should be renamed to `students/authenticate`.

**Comment by VictorAlagwu** [comment]
Done, check commit

**Comment by shalvah** [comment]
Fixed in #10
