### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by shalvah** [shalvah/unn-api#9]
I'm not sure, really 😕 

Okay, seriously. They probably changed something in the frontend of the school portal, so it's broken. I'll try to get to it when I'm free, but can someone check it out?

**Comment by VictorAlagwu** [comment]
I try using PostMan to test the API, but I am getting 
"message": "authentication failed: incorrect username or password"
even when the login details are correct

**Comment by shalvah** [comment]
Ah. Same thing here. I guess something has changed, and the web scraper is failing. (This is why we need #4)
I'll get on updating this when I have time, but anyone who wants can pick it up.

**Comment by shalvah** [comment]
I'm thinking of reimplementing the web scraper with something like https://github.com/FriendsOfPHP/Goutte.

**Comment by VictorAlagwu** [comment]
I will go through it and see, if i can do something

**Comment by shalvah** [comment]
Fixed in 6eb66b86fcdd30d45a859cad6968f8c8fcbfcfbd. Works now!
